// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for web - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

//  apiKey: "AIzaSyBKlBGzyDkmKS_hLImtM4lzE7EfyXsjSXc",
//   authDomain: "frames-1e3eb.firebaseapp.com",
//   projectId: "frames-1e3eb",
//   storageBucket: "frames-1e3eb.appspot.com",
//   messagingSenderId: "112888667449",
//   appId: "1:112888667449:web:a91e456514a8a444095ce8",
//   measurementId: "G-4LLZW58W9N"

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKlBGzyDkmKS_hLImtM4lzE7EfyXsjSXc',
    appId: '1:112888667449:web:a91e456514a8a444095ce8',
    messagingSenderId: '112888667449',
    projectId: 'frames-1e3eb',
    storageBucket: 'frames-1e3eb.appspot.com',
  );

  
}
